networks:
  docker-net:
    external: true

services:
  traefik:
    image: traefik:3
    restart: unless-stopped
    command: --configFile=/etc/traefik/traefik.yaml
    networks:
      - docker-net
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock
