providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true

http:
  routers:

entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true

log:
  level: INFO

accessLog: {}
